name: Snake Eating Contribution Graph

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure git user
        run: |
          git config --global user.name "Dolezar Mabunda"
          git config --global user.email "itsrensei@gmail.com"

      - name: Modify contribution graph
        run: |
          # Create a new style element with the snake-eating CSS
          echo '<style>.js-calendar-graph-svg{transform:rotate(-45deg);}.ContributionCalendar-day{transform:rotate(45deg)!important;transform-origin:50% 50%;}</style>' > style.css
          
          # Commit and push the changes
          git add style.css
          git commit -m "Add snake-eating contribution graph"
          git push origin main
